version: '3'

services:
  parser:
    build: .
    environment:
      DB_DIALECT: "postgres"
      DB_URI: |
        host=postgres
        port=5432
        user=${POSTGRES_USER:-velobike}
        password=${POSTGRES_PASSWORD:-velobike}
        dbname=${POSTGRES_DB:-velobike}
        sslmode=disable
      TZ: "Europe/Moscow"
      BACKUP_DIR: "/data"
    depends_on:
      - "postgres"
    volumes:
      - ./data:/data
    command: wait-for-it postgres:5432 -- ./velobike-parser
    restart: unless-stopped

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-velobike}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-velobike}
      POSTGRES_DB: ${POSTGRES_DB:-velobike}
      PGDATA: /data/postgres
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    volumes:
      - postgres:/data/postgres
    ports:
      - "54321:5432"
    restart: unless-stopped

volumes:
  postgres: